CREATE TABLE post
(
    id      INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title   VARCHAR(255),
    author  VARCHAR(255),
    created TIMESTAMP,
    content VARCHAR(255),
    CONSTRAINT pk_post PRIMARY KEY (id)
);

CREATE TABLE users
(
    id            INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username      VARCHAR(255),
    password_hash VARCHAR(255),
    created       TIMESTAMP,
    admin         BOOLEAN                              NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE INDEX idx_77584fbe74cc86922be2a3560 ON users (username);
