CREATE TABLE post
(
    id      INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title   VARCHAR(255),
    author  VARCHAR(255),
    created TIMESTAMP,
    content VARCHAR(255),
    CONSTRAINT pk_post PRIMARY KEY (id)
);

